### ISSUE TITLE
Todo for 1.6.0

### ISSUE THREAD

**Issue by JuiceyBeans** [JuiceyBeans/JuiceyTweaks#5]
- [ ] Rework path speed mixin
- [ ] Wearing wither skull does withering
- [ ] Impaling tridents do damage to any mobs that are in water
- [x] #6
